# Generated by Django 3.1.2 on 2020-11-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwenyu', '0004_auto_20201105_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_contact',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
